language: php
php:
- 5.5
- 7.0

env:
- BD=pgsql

before_install:
- sudo apt-get update -q
- sudo apt-get install ruby-full -y
- gem install sass

install: ./install-dependencies.sh

before_script: true

script: 
- phpunit Test.php
- phpunit Usuario.php
- phpunit Persona.php
- phpunit Pedido.php
- phpunit menu.php
- phpunit plato.php
- phpunit detallepedido.php

